// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvo7m6dY9OBhSWwXZ9W_KFLo_UTEG8I-U',
    appId: '1:953616558612:web:6ca7e06543a755c9621501',
    messagingSenderId: '953616558612',
    projectId: 'financial-app-9f92b',
    authDomain: 'financial-app-9f92b.firebaseapp.com',
    storageBucket: 'financial-app-9f92b.firebasestorage.app',
    measurementId: 'G-ZWTN57V1EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2wcBZn8uJ2sxFQiZPX6Ejn62kbY7B0M',
    appId: '1:953616558612:android:e18e6e233beb87b3621501',
    messagingSenderId: '953616558612',
    projectId: 'financial-app-9f92b',
    storageBucket: 'financial-app-9f92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQbelPCy2vfXJf9bNGgydEeRZj8xSnpo',
    appId: '1:953616558612:ios:81f53ef5bc2a983f621501',
    messagingSenderId: '953616558612',
    projectId: 'financial-app-9f92b',
    storageBucket: 'financial-app-9f92b.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQbelPCy2vfXJf9bNGgydEeRZj8xSnpo',
    appId: '1:953616558612:ios:81f53ef5bc2a983f621501',
    messagingSenderId: '953616558612',
    projectId: 'financial-app-9f92b',
    storageBucket: 'financial-app-9f92b.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvo7m6dY9OBhSWwXZ9W_KFLo_UTEG8I-U',
    appId: '1:953616558612:web:47ca3d14bfafb2c8621501',
    messagingSenderId: '953616558612',
    projectId: 'financial-app-9f92b',
    authDomain: 'financial-app-9f92b.firebaseapp.com',
    storageBucket: 'financial-app-9f92b.firebasestorage.app',
    measurementId: 'G-ZP4QH0FXL4',
  );
}
